cc/camcap.hpp
Identação refeita e variáveis redundantes removidas (testado).
=> Camcap Reorganizado

buildVSSS.sh, cc/TestFrame.cpp, cc/TestFrame.hpp, cc/controlGUI.hpp, cc/strategyGUI.hpp
- TestFrame adicionado as abas Strategy e Control.
- Para ajustar as barras HScale, é só alterar os parâmetros dentro da função configureTestFrame (dentro do controlGUI ou strategyGUI).
- Para pegar os valores das barras HScale, utilize o testFrame.getValue(index), onde index é o índice da barra hscale (de 0 a 4).
=> TestFrame adicionado para testar variáveis do código

.gitignore, cc/camcap.hpp, cc/controlGUI.hpp, cc/vision/vision.cpp, cc/vision/vision.hpp, docs/README.md
- Adicionado a funcionalidade de gravar vídeos e imagens da câmera. (Não integrado a interface ainda)
- Correções na leitura da bateria.
- Ajustes no .gitignore para não enviar vídeos e imagens salvas da câmera para o repositório.
- Ajustes no cálculo do FPS (o código faz a mesma coisa, porém está escrito com menos leitoagem).
=> Vision capture

Makefile, buildVSSS.sh, cc/camcap.hpp, cc/controlGUI.hpp, cc/vision/vision.cpp, cc/vision/vision.hpp, cc/vision/visionGUI.cpp, cc/vision/visionGUI.hpp, pack-capture-gui/capture-gui/V4LInterface-aux.cpp, pack-capture-gui/capture-gui/V4LInterface-events.cpp, pack-capture-gui/capture-gui/V4LInterface.hpp
- Aba Vision adicionada
- HSV Calib. movido para aba Vision
- Novo Frame de captura de vídeo e imagem da Câmera
- Auto gravação de vídeo ao começar a o jogo
- Auto encerramento de vídeo ao pausar o jogo
- Quick Actions (Save/Load) movido para o Frame Info (em baixo da imagem da câmera)
=> VisionGUI adicionado

cc/camcap.hpp, cc/controlGUI.hpp, cc/strategyGUI.hpp, pack-capture-gui/capture-gui/ImageView.hpp
Agora é possível salvar formações de bola parada para execução durante o jogo, como posições de início de jogo, cobranças de pênalti, etc.
O código está pronto mas ainda não está sendo utilizado para posicionamento dos robôs reais, isso deve ser feito pela estratégia.
=> Novo sistema de criação de formações

cc/vision/vision.cpp, cc/vision/vision.hpp, cc/vision/visionGUI.cpp
Ambos não estão sendo utilizados atualmente.
=> Vision: FindElements e cor rosa comentados

cc/SerialW.cpp
Correção na condição de envio das mensagens: troca de x (repetido) por y.
=> Pequena correção no SerialW

cc/Messenger.cpp, cc/Messenger.h, cc/Xbee.cpp, cc/Xbee.h
- Corrige bug na interface de bateria
- Simplifica o código do Messenger e do Xbee
=> Correção na interface de bateria

cc/Strategy.cpp, cc/Strategy.hpp
=> Strategy organize

cc/CamCap.cpp, cc/Strategy.cpp, pack-capture-gui/capture-gui/Robot.hpp
- Melhora alguns parâmetros da estratégia para melhor desempenho
- Corrige o desenho dos targets: se o robô tiver o tipo de comando VECTOR, desenha uma linha verde indicando o vetor ao invés do círculo de target (VECTOR não possui target)
=> Corrige parâmetros da estratégia.

cc/Strategy.cpp, cc/Strategy.hpp, cc/StrategyGUI.cpp, cc/StrategyGUI.hpp
- Adiciona opção na interface de desativar half_transition, full_transition e transition_mindcontrol
- Corrige bug no valor padrão de spin_clockwise e spin_clockwise (valor padrão deve ficar no .hpp)
=> Opcão de desativar transitions

.travis.yml, docs/README.md
- criação da imagem do repositório no novo docker hub
- correção do link da badge
=> Correcao travis

cc/CamCap.cpp, cc/jsonSaveManager.cpp, cc/vision/gmm.cpp, cc/vision/gmm.hpp, cc/vision/vision.cpp, cc/vision/vision.hpp, cc/vision/visionGUI.cpp, cc/vision/visionGUI.hpp, pack-capture-gui/capture-gui/V4LInterface-aux.cpp, pack-capture-gui/capture-gui/V4LInterface-events.cpp
- Retirada da opção do HSV
- Correção de parâmtros da Visão
- Mudança de estilo de código
- GMM desabilitado na aba Vision
=> Retirada do HSV da Visão e alguns ajustes

cc/jsonSaveManager.cpp, cc/vision/vision.cpp, cc/vision/vision.hpp, cc/vision/visionGUI.cpp, cc/vision/visionGUI.hpp
- Criação dos enums Limit e Color
- Adicição da expressão const onde é recomendado
- Renomeação de algumas variáveis
- Criação do namespace vision
=> Melhorias no código vision

CMakeLists.txt, cc/Strategy2/Defender.cpp, cc/Strategy2/Defender.hpp
Novo código base do defensor para o novo código da estratégia.
=> Adiciona a classe Defender

buildVSSS.sh
Ajustes no script buildVSSS.sh, para que o TravisCI consiga detectar erros de compilação
=> Correção no TravisCI

CMakeLists.txt, cc/CamCap.cpp, cc/CamCap.hpp, cc/main.cpp, pack-capture-gui/capture-gui/RobotGUI.cpp, pack-capture-gui/capture-gui/RobotGUI.hpp, pack-capture-gui/capture-gui/V4LInterface-aux.cpp, pack-capture-gui/capture-gui/V4LInterface-events.cpp, pack-capture-gui/capture-gui/V4LInterface.hpp
- Para as resoluções de 1360x768 e 1600x900, as informações do robô foram movidas para uma nova aba Robot
- Para resoluções maiores (como full HD), a interface continua praticamente a mesma de antes
- Pequenas melhorias no código
=> Arruma o problema do programa não caber em telas de resoluções menores

cc/CamCap.cpp, cc/Geometry/Geometry.cpp, cc/Geometry/Geometry.h
Comando Vector/Orientation: desenha um segumento de reta para a direção que o robô tem de ir
Comando None: desenha um X na posição do robô
Demais comandos: desenha um círculo com o alvo
=> Reabilita o desenho de targets para nova estratégia

cc/Geometry/Geometry.cpp, cc/Geometry/Geometry.h
- Corrige bugs no distance_x e na soma de vetor com ponto
- Cria wrap(double theta) que faz o angulo ficar entre -PI e PI
=> Ajustes no Geometry

pack-capture-gui/capture-gui/V4LInterface-aux.cpp, pack-capture-gui/capture-gui/V4LInterface.hpp
Corrige bug na inicialização de variáveis que causava baixo fps na câmera
=> Correção de bug

cc/Strategy2/Field.cpp, cc/Strategy2/Field.h, cc/Strategy2/Goalkeeper.cpp
+ Adiciona OurUpperCorner e OurLowerCorner no enum dos Locations do field
+ Adiciona a função match_y() no field para verificar se alguma posição está com mesmo valor de y de um Location do campo
+ Corrige alguns valores do field
=> Corrige os behaviors do goalkeeper.

CMakeLists.txt, cc/CamCap.cpp, cc/CamCap.hpp, cc/vision/gmm.cpp, cc/vision/gmm.hpp, cc/vision/vision.cpp, cc/vision/vision.hpp, pack-capture-gui/capture-gui/ImageArt.cpp, pack-capture-gui/capture-gui/ImageArt.hpp
Os desenhos na imagem foram retirados do camcap e colocados em ImageArt.hpp, sob o namespace art.
=> Retira as funções do desenho na imagem do camcap e os coloca no namespace art

buildVSSS.sh, runVSSS.sh
- buildVSSS.sh: adiciona a opção -p no mkdir para caso já exista a pasta build/
- runVSSS.sh: adiciona um shebang
=> Pequenas correções nos scripts de build e run

cc/vision/vision.hpp, cc/vision/visionGUI.cpp, pack-capture-gui/capture-gui/V4LInterface-aux.cpp, pack-capture-gui/capture-gui/V4LInterface-events.cpp, pack-capture-gui/capture-gui/V4LInterface.hpp
Corrigir checkboxes enable to disable
Issue #117
=> Corrigir checkboxes enable to disable

.idea/codeStyles/Project.xml, CMakeLists.txt, cc/CamCap.cpp, cc/CamCap.hpp, cc/Geometry/Geometry.cpp, cc/Geometry/Geometry.h, cc/Messenger.h, cc/Strategy2/Attacker.cpp, cc/Strategy2/Goalkeeper.cpp, cc/Strategy2/Robot2.h, cc/TestOnClick.cpp, cc/TestOnClick.hpp, cc/controlGUI.cpp, cc/controlGUI.hpp, cc/main.cpp, cc/vision/tag.hpp, pack-capture-gui/capture-gui/ImageArt.cpp, pack-capture-gui/capture-gui/ImageArt.hpp, pack-capture-gui/capture-gui/ImageView.cpp, pack-capture-gui/capture-gui/ImageView.hpp, pack-capture-gui/capture-gui/V4LInterface-aux.cpp, pack-capture-gui/capture-gui/V4LInterface-events.cpp, pack-capture-gui/capture-gui/V4LInterface.hpp
- Para usar, deve apertar o botão "Start Test On Click"
- Botão "Start Test On Click" está apenas disponível se tiver um xbee conectado
- O robô a ser testado deve ser selecionado clicando em cima dele na imagem com o botão esquerdo do mouse
- O alvo (target) da onde o robô deve ir deve ser selecionado clicando em cima na imagem com o botão direito do mouse
- É possível ajustar o ângulo alvo pela barra de escala. O novo ângulo só é realmente estabelecido depois de apertar o botão "Set".
Existe uma caixa de seleção para selecionar o comando que será enviado ao robô. As opções são:
- **Stop (None):** Manda o robô ficar parado. Na prática, não é enviado nenhum comando ao robô (logo, ele fica parado).
- **Go to target direction (Vector):** O robô vai em linha reta na direção selecionada. Usa …
=> Novo Test On Click

pack-capture-gui/capture-gui/RobotGUI.cpp, pack-capture-gui/capture-gui/RobotGUI.hpp
Automatizar mudança para seleção do robô de modo a não permitir duplicações das tags
=> Organizacao automatica da identificacao dos robos

pack-capture-gui/capture-gui/V4LInterface-aux.cpp, pack-capture-gui/capture-gui/V4LInterface-events.cpp, pack-capture-gui/capture-gui/V4LInterface.hpp, pack-capture/capture/v4lcap.cpp, pack-capture/capture/v4lcap.hpp
Adicionamos o botão "Refresh"  na aba Capture do programa. Sua funcionalidade se assemelha ao botão refresh do Xbee
=> Adiciona botão refresh para câmera.

cc/controlGUI.cpp, cc/controlGUI.hpp
- Antiga frame Serial separada em frame Radio Connection e frame Commands.
- Adicionado borda em todas as frames da aba Control
- Alguns widgets foram alterados para melhor uso
=> Melhora Interface da Aba Control
